### ISSUE TITLE
Aurelia knockout crashes in Safari

### ISSUE THREAD

**Issue by Isoldhe** [code-chris/aurelia-knockout#44] opened 2022-09-22 14:41 UTC
Since the release of iOS 16, our aurelia-knockout pages stopped working in Safari. If I delete the 'knockout' attribute, the page loads. Obviously the knockout functionality doesn't work anymore if I do that.

The only errors I get are in the console, but they don't refer to this package. That's why it took me a long time to figure out the page crashes on the knockout attribute. It says there's an error in the app-router... and also, the page was blocked due to insecure content from the aurelia router which doesn't make sense. Pages without aurelia-knockout do load, so the router works fine.

![Safari-errors](https://user-images.githubusercontent.com/32617277/191763439-cd8482a3-5f50-4d32-bcaa-bd48e3ba2c5c.png)

On one page I replaced the aurelia-knockout functionality for pure Aurelia data binding functionality and that fixes the page. However, a large portion of our website is build with aurelia-knockout, so replacing with Aurelia functionality will take weeks.

Is this a known issue?
Or if it works for others in iOS / Safari 16, can I see an example application? Could be something else that's causing this, but I'm not sure where to go from here at this point.

Our web application is build with .Net 4.8 framework that loads the aurelia scripts in the index.cshtml, bundled with webpack. I attached the console errors I see in Safari 16. Below is my package.json:

```
{
  "name": "application",
  "description": "An Aurelia client application.",
  "version": "0.1.0",
  "repository": {
    "type": "???",
    "url": "???"
  },
  "license": "MIT",
  "dependencies": {
    "@appex/aurelia-dompurify": "^0.5.0",
    "@types/sizzle": "^2.3.3",
    "aurelia-animator-css": "^1.0.4",
    "aurelia-bootstrapper": "^2.4.0",
    "aurelia-fetch-client": "^1.8.2",
    "aurelia-google-analytics": "^2.5.0",
    "aurelia-knockout": "^2.4.2",
    "aurelia-polyfills": "^1.3.4",
    "aurelia-validation": "^2.0.0-rc2",
    "babel-eslint": "^10.1.0",
    "deepmerge": "^4.2.2",
    "eslint": "^8.23.1",
    "flatpickr": "^4.6.13",
    "font-awesome": "^4.7.0",
    "jquery": "^3.6.1",
    "knockout-mapping": "^2.6.0",
    "knockout-validation": "^0.1.1",
    "material-components-web": "^3.2.0",
    "moment": "^2.29.4",
    "moment-locales-webpack-plugin": "^1.2.0",
    "process": "^0.11.10",
    "remarkable": "^1.7.1"
  },
  "devDependencies": {
    "@types/knockout": "^3.4.72",
    "@types/lodash": "^4.14.185",
    "@types/node": "^18.7.18",
    "@types/webpack": "^5.28.0",
    "aspnet-webpack": "^3.0.0",
    "aurelia-cli": "^3.0.1",
    "aurelia-loader-nodejs": "^1.1.0",
    "aurelia-pal-nodejs": "^3.0.0-rc.1",
    "aurelia-testing": "^1.1.0",
    "aurelia-webpack-plugin": "^5.0.4",
    "clean-webpack-plugin": "^4.0.0",
    "copy-webpack-plugin": "^11.0.0",
    "css-loader": "^6.7.1",
    "del": "^6.1.1",
    "duplicate-package-checker-webpack-plugin": "^3.0.0",
    "expose-loader": "^4.0.0",
    "gulp": "^4.0.2",
    "gulp-protractor": "^4.1.1",
    "gulp-rename": "^2.0.0",
    "html-loader": "^4.1.0",
    "html-webpack-plugin": "^5.5.0",
    "istanbul-instrumenter-loader": "^3.0.1",
    "jest": "^29.0.3",
    "jest-cli": "^29.0.3",
    "json-loader": "^0.5.7",
    "mini-css-extract-plugin": "^2.6.1",
    "minimatch": "^5.1.0",
    "node-sass": "^7.0.3",
    "nps": "^5.10.0",
    "nps-utils": "^1.7.0",
    "opn": "^6.0.0",
    "plugin-error": "^2.0.0",
    "sass-loader": "^13.0.2",
    "script-loader": "^0.7.2",
    "style-loader": "^3.3.1",
    "through2": "^4.0.2",
    "ts-jest": "^29.0.1",
    "ts-loader": "^9.4.0",
    "ts-node": "^10.9.1",
    "typescript": "^4.8.3",
    "vinyl-fs": "^3.0.3",
    "wait-on": "^6.0.1",
    "webpack": "^5.74.0",
    "webpack-bundle-analyzer": "^4.6.1",
    "webpack-cli": "^4.10.0",
    "webpack-dev-server": "^4.11.1",
    "webpack-hot-middleware": "^2.25.2"
  },
  "jest": {
    "modulePaths": [
      "<rootDir>/src",
      "<rootDir>/node_modules"
    ],
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "transform": {
      "^.+\\.ts$": "ts-jest"
    },
    "testRegex": "\\.spec\\.(ts|js)$",
    "setupFiles": [
      "<rootDir>/test/jest-pretest.ts"
    ],
    "testEnvironment": "node",
    "collectCoverage": true,
    "collectCoverageFrom": [
      "src/**/*.{js,ts}",
      "!**/*.spec.{js,ts}",
      "!**/node_modules/**",
      "!**/test/**"
    ],
    "coverageDirectory": "<rootDir>/test/coverage-jest",
    "coverageReporters": [
      "json",
      "lcov",
      "text",
      "html"
    ]
  },
  "engines": {
    "node": ">= 6.0.0"
  },
  "scripts": {
    "start": "nps",
    "test": "nps test"
  },
  "main": "dist/app.bundle.js"
}

```

**Comment by ckotzbauer** [comment] 2022-09-22 17:34
Hi @Isoldhe,
thanks for opening this issue.

Safari issues are always not that easy. Safari is often not well tested.
I have a few questions:
- You wrote "iOS", so you mean a mobile device (iPhone or iPad)? If yes, does this also occur on macOS?
- The issues don't occur with Safari 15? (without code-changes to your project)
- Can you create a small repro repository (without .NET, only a small Aurelia/Knockout app)?

> Is this a known issue?
Or if it works for others in iOS / Safari 16, can I see an example application?

I don't know about this issue and I personally don't developed for Safari for years.
But, of course: Maybe Safari is buggy and will be patched soon.

If you can create a reproduction, this would be really great. Then we have maybe a chance to solve this, but it may take some time. Without the repro it is very hard to say anything about this.

**Comment by iVicm** [comment] 2022-09-22 22:46
Hello all,

In our application we are facing same issue, I can add more infirmation:

- In our case, on mobile device works as expected. Fails on Safari's desktop version. Also we used playwright with webkit 16 and we observe same issue (Windows 10)
- Doesn't occur with Safari's older versions. Only Safari 16

Side note, we are using aurelia-knockout v.2.0.2

**Comment by ckotzbauer** [comment] 2022-09-23 04:40
> Also we used playwright with webkit 16 and we observe same issue (Windows 10)

You mean Safari 16 on Windows 10?


> Side note, we are using aurelia-knockout v.2.0.2

Please update to the latest version, to be sure that there are no other side-effects.
If you can provide a repro repository as well, this would be great.

**Comment by Isoldhe** [comment] 2022-09-23 08:31
Hi @ckotzbauer,
Thanks for the quick reply.

I created a [repro with aurelia](https://github.com/Isoldhe/aurelia-knockout-mre) only. .Net wasn't necessary to reproduce the problem. If I run this project on a Mac I see a white screen and console errors.

The issue appears in Safari 16 only. It works in V15. It happens both on MacOs with Safari 16 and iPhones that have iOS 16 on it.

**Comment by ckotzbauer** [comment] 2022-09-23 08:58
Thanks for the repo, I can reproduce it.

**Comment by ckotzbauer** [comment] 2022-09-23 09:19
The problem is not part of aurelia-knockout. When I set a breakpoint at the error line, you can see that this is in the middle of the knockout stack.
This is also the reason, why the error is gone when you remove the `knockout` attribute, cause knockout is not called then at all.
As knockout is unmaintained for about three years, I think there won't be a fix for this.

**Comment by Isoldhe** [comment] 2022-09-23 09:39
Yeah, I noticed the last knockout release was 3 years ago... I feared as much. We're going to remove knockout from our project. Thanks for having a look!

**Comment by iVicm** [comment] 2022-09-23 11:46
> > Also we used playwright with webkit 16 and we observe same issue (Windows 10)
> 
> You mean Safari 16 on Windows 10?
> 
We tested on MacOS and checked with other browsers and OS.

We also are going to remove knockout

Thanks for your help on this!

**Closed as completed** 2022-09-23 11:54 UTC
